server.port=8081

spring.datasource.url=jdbc:mysql://crossover.proxy.rlwy.net:25945/railway?useSSL=true&requireSSL=true&verifyServerCertificate=false
spring.datasource.username=root
spring.datasource.password=efMYlHhteQvTZJNBJCVISxjQgiKElFLr

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true